### ISSUE TITLE
Recherche par dates et étendue

### ISSUE THREAD

**Issue by epointal** [terresolide/gnss-components-vjs#10]
Pour le moment, la recherche par date et étendue:
recherche 

- s'il y a des données après la date de début
- s'il y a des données avant la date de fin
- si l'étendue temporelle est comprise entre x années et y années
Mais on peut très bien avoir la configuration ci-dessous:
![etendue-temporelle](https://github.com/terresolide/gnss-components-vjs/assets/9362043/ff760749-0089-4cc2-91c4-806b702badf2)

Voir issue #7

**Comment by RaphaelGrandin** [comment]
Il me semble que le schéma indique qu'un OU LOGIQUE associe les deux premières conditions dans la manière dont répond la plateforme. Il vaudrait mieux appliquer un ET LOGIQUE entre toutes les conditions, ce qui serait plus intuitif. Par contre, il faut alors bien veiller à ce que les bornes et les valeurs par défaut soient suffisamment larges pour ne pas exclure de données.

**Comment by epointal** [comment]
Il y a un  ET entre mes conditions, mais je testais juste si il existait des données après la date de début **et** si il existait des données avant la date de fin...
J'ai modifié mes conditions,  il y a des données  à partir de la date de début **et** il y a des données jusqu'à la date de fin (mais il peut y en avoir après)
=> Voir ce que ça donne, je viens de mettre à jour

**Comment by RaphaelGrandin** [comment]
Ok j'ai compris, désolé. Je crois que je confonds "outil de recherche" et "outil de subsetting".
