### ISSUE TITLE
page de visu un peu grande

### ISSUE THREAD

**Issue by pbosser** [terresolide/gnss-components-vjs#14]
petit point esthétique : la page de visu est un peu grande, avec beaucoup de blanc... les infos y paraissent perdues

![Screenshot 2023-05-30 at 17-58-56 Visualisation GNSS – ForM@Ter](https://github.com/terresolide/gnss-components-vjs/assets/81028960/2b2067e3-eafe-46a2-a2bc-d3228d182944)

**Comment by pbosser** [comment]
ok, c'est normal, ça permet de laisser de la place pour afficher plusieurs solutions, j'aurais du lire la doc avant !

**Comment by epointal** [comment]
Je regarderai si je peux agrandir le graphique et la carte quand l'écran est grand et qu'il n'y a qu'une solution

**Comment by epointal** [comment]
Petite amélioration en agrandissant les produits....
