### ISSUE TITLE
Probleme d'affichage de la liste des stations selectionnées

### ISSUE THREAD

**Issue by SylvainCLS** [terresolide/gnss-components-vjs#18]
Quand on sélectionne 62 stations (affichage de 25 par pages) :https://www.poleterresolide.fr/visualisation-gnss/#/files?network=IGS,EPN&page=2&maxRecords=25 
- la première page donne Results: 1 to 25 among 62 
- la suivante donne Results: 26 to 45 among 62
- la suivante ne liste rien et marque Results: 51 to 50 among 62  (bizarre !!) ou sont les stations de 46 à 62 ?

**Comment by epointal** [comment]
Gros bug

**Comment by epointal** [comment]
Manque comme un DISTINCT dans la requête COUNT

**Comment by epointal** [comment]
Back maj
