### ISSUE TITLE
Nom du bouton "Show"

### ISSUE THREAD

**Issue by SylvainCLS** [terresolide/gnss-components-vjs#19]
Dans le popup affiché pour les détails  d'une série/station  (exemple MANS00FRA) ,  la page propose d'afficher les "Nearest Stations", 
ici MAN200FRA. On s'attend à ce que e bouton "Show" montre les détails de la station en question (ce que fait le clic sur le nom de la solution)  mais en fait ca montre la position sur la carte.
Pour plus de clarté , peut être remplacer "Show" par "Show on map" ?

**Comment by epointal** [comment]
Fait et maj
