### ISSUE TITLE
Typos / noms des champs

### ISSUE THREAD

**Issue by RaphaelGrandin** [terresolide/gnss-components-vjs#2]
Il y a deux typos dans le panneau de recherche:
- le bouton "Resest" devrait s'écrire "Reset",
- le champ "Extend" devrait s'écrire "Extent".

![capture2](https://github.com/terresolide/gnss-components-vjs/assets/17451250/6205cb42-6714-4a05-9f29-aba75e4ccd1d)

**Comment by epointal** [comment]
Ok version 1.2.5
