### ISSUE TITLE
Téléchargement des données de plusieurs solutions

### ISSUE THREAD

**Issue by SylvainCLS** [terresolide/gnss-components-vjs#20]
Quand on a sélectionné plusieurs stations (exemple https://www.poleterresolide.fr/visualisation-gnss/#/files?center=-5.833740234375001,49.35375571830993&radius=333.165 ) , y a t'il une possibilité de télécharger l'ensemble des séries d'un coup ? On en avait parlé mais là je n'ai pas retrouvé comment faire à part télécharger une par une les séries.

**Comment by epointal** [comment]
Semi solution, voir le bouton sur la page liste. Mais ne télécharge que les fichiers visibles de la liste: 
https://www.poleterresolide.fr/visualisation-gnss/#/files

**Comment by SylvainCLS** [comment]
Chouette: c'était juste une proposition ;  je viens de le tester ca fonctionne.

**Comment by epointal** [comment]
Je clos pour le moment. Je pense que la question reviendra
