### ISSUE TITLE
Bugs / fonctions non disponibles

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#22]
- lorsque l'on clique sur une station, la série temporelle apparait sous forme de bulle, si on clique une 2eme fois, la bulle se ferme. Si on re-clique pour la même station pour la rouvrir, cela ne fonctionne pas.

- Il est écrit en p.5 de la doc que pour la ‘Selected area’ il est possible de des/sélectionner les stations MOBILE/PERMANENT/Unknown mais ce n’est pas le cas sur mon navigateur (SAFARI 16.3).
 
-  il est écrit dans la doc (p.5) qu’en cliquant sur une station parmi la selection (faite par l’outil selection rectangulaire ou circulaire), ca doit ouvrir un popup avec un carrousel avec les X stations sélectionnées, ca ne fonctionne pas sur mon navigateur, le popup contient uniquement la station cliquée, pas de carrousel contenant les autres stations.

**Comment by epointal** [comment]
Le point 1 est un bug (Je crée une nouvelle issue #30)
Le point 2: les statuts des stations ont été supprimés (demande lors de la réunion pré beta test)
Le point 3: c'est sans doute mal exprimé: le caroussel contient les quicklooks des séries temporelles de la station (Voir la popup de la station BRST: https://www.poleterresolide.fr/visualisation-gnss/#/?bounds=-11.195068359375002,45.97406038956239,2.7246093750000004,51.998410382390325&selected=24)
![popup](https://github.com/terresolide/gnss-components-vjs/assets/9362043/aebde7a1-c792-4650-b130-2f5b3f86ac18)

**Comment by EmilieKlein** [comment]
Pour le point 3: ok compris, ca ne concerne pas la selection de plusieurs stations....
dommage, je le met en suggestion ! ;)
