### ISSUE TITLE
Suggestions: Outils selection geographique/recherche sur la carte

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#23]
- Lorsqu’une recherche (via le formulaire) est infructueuse, il ne se passe rien, il n’y a aucune station affichée, mais aucun message d’avertissement non. Ca serait sans doute utile de signifier à l’utilisateur de modifier sa recherche.

- l'outil selection géographique n'a pas l'air de fonctionner sur mon navigatrice (voir issue 'bug' mais s'il fonctionnait, il pourrait être utile de proposer une option pour télécharger les .pos des séries temporelles sélectionnées d'un coup. Pourquoi pas aussi une option permettant d’ouvrir les page de toutes les stations sélectionnées sur des nouveaux onglets pour pouvoir visualiser les series temporelles.

**Comment by epointal** [comment]
Je crée une nouvelle issue pour le cas "aucune station" issue #29 .
Pour le second point. Il y a un bouton "Télécharger tous" mais sur la vue en liste. 
Pour le point: ouvrir dans un nouvel onglet les stations. (Faire attention au cas 3000 stations dans un nouvel onglet)

**Comment by epointal** [comment]
Je ferme cette issue (Voir les issues ouvertes sur les sujets). Pour l'utilisation de Safari...
