### ISSUE TITLE
Suggestions: Ouverture des pages stations dans un nouvel onglet ?

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#24]
Il serait pratique de pouvoir ouvrir une page station dans un nouvel onglet et non à la place de la carte : pour le moment (en tout cas sur mon navigateur Safari 16.3), il apparait nécessaire de fermer la page de la station pour revenir à la carte, pour pouvoir en ouvrir une autre. Les raccourcis (pomme+clic) ou clic droit->'ouvrir dans un nouvel onglet' ne fonctionne par ailleurs pas, cela signifie-t-il qu’on ne peut pas ouvrir 2 stations en meme temps ? 
Je pense que ce serait une option utile et importante, on cherche souvent a comparer plusieurs series temporelles (de stations proches par ex.) entre elles.

**Comment by epointal** [comment]
Je dois pouvoir ajouter un menu sur le click droit => ouvrir dans un nouvel onglet.
