### ISSUE TITLE
Bug sitelog

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#27]
Pas sure que ca soit un bug (je ne connais pas bien les formats m3g) mais quand je cliques sur ‘sitelog’ j’obtiens l’imprim’ecran joint… 
<img width="1512" alt="Capture d’écran 2023-06-06 à 11 48 34" src="https://github.com/terresolide/gnss-components-vjs/assets/30504591/6cfa3152-0a0e-4c64-8580-cd89ffb5d589">

**Comment by epointal** [comment]
Ah il s'agit de la page du M3G . Le format est xml mais votre navigateur ne l'affiche pas bien. C'est plus clair avec firefox:
![Capture du 2023-06-08 08-59-48](https://github.com/terresolide/gnss-components-vjs/assets/9362043/7700504f-5502-45ae-93f9-219804cddc8d)

**Comment by EmilieKlein** [comment]
ok, si c'est qqch qui ne peut pas être modifié du coté du développement de l'interface, il faudrait sans doute faire une notification disant que sous certains navigateurs, le site log n'apparait pas formaté et recommander l'utilisation de certains navigateurs pour une expérience optimale!

**Comment by epointal** [comment]
J'ai modifié pour mettre le format texte
