### ISSUE TITLE
Bug ? Affichage changements de matériel

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#28]
Les matériels change sont indiqués sur les series temporelles SPOTGINS mais visiblement pas sur les series temporelles GAMIT-GLOBK - voir ex MICH:
<img width="1512" alt="MICH_SPOTGINS" src="https://github.com/terresolide/gnss-components-vjs/assets/30504591/c4b5b3c4-358a-41a4-ad37-580609bd9b7d">
<img width="1512" alt="MICH_GG" src="https://github.com/terresolide/gnss-components-vjs/assets/30504591/cd53bc4a-f98b-4294-a511-ad64077e0b7f">
<img width="1512" alt="MICH_principal" src="https://github.com/terresolide/gnss-components-vjs/assets/30504591/d5906c3a-8805-42b8-acdc-1c8271ebbfbe">

**Comment by epointal** [comment]
Oui, car ils n'ont pas été fournis.
Chaque "fournisseur" doit transmettre les dates remarquables qu'il a retenu. Apparemment ce ne sont pas  forcément les mêmes.

**Comment by EmilieKlein** [comment]
Les dates de changement de matériels sont les mêmes quelque soit le traitement (GAMIT-GLOBK ou SPOTGINS) et ont forcement du être retenues et utilisées dans le traitement GAMIT-GLOBK (sous la forme d'un fichier appelé 'station.info') , ce sont effectivement les fournisseurs qui n'ont pas du les fournir mais ca devrait être requis pour affichage de sorte que ces changements de matériels fassent partie des Metadonnées des stations

**Comment by alvarosantamariagomez** [comment]
Les dates des changements sont les mêmes effectivement, mais l'idée ici est d'afficher les dates des changements pris en compte dans chaque traitement, ce qui peut être différent.
Du coup ça voudrait le coup de mentionner cet info sur l'affichage si ce n'est pas fait.

**Comment by EmilieKlein** [comment]
Je pense qu'il faut les afficher tous, on peut identifier ceux pris en compte ou non... meme si j'ai du mal a comprendre ce que ca signifie. Mais, chacune des actions majeures (ie chgt de récepteurs ou antennes... a discuter pour les upgrades de firmware...) devrait être recensées et l'information mise a disposition de l'utilisateur de la série temporelle (comme NGL le fait !)

En récupérant le station.info ou l'equivalent en GINS pour chacune des solutions, ca devrait être assez facile a extraire.
--> ces fichiers devraient faire partie des deliverables pour integration d'une solution a l'application.

**Comment by alvarosantamariagomez** [comment]
Afficher tous les sauts c'est simplement impossible. De mémoire, dans le repro2 il y avait 1/3 des discontinuités inconnues ...
Donc, on affiche tous les changements recensés (= pris en compte) dans les métadonnées qu'on a sur GAMIT ou GINS au moment de faire le calcul (date indiquée dans l'entête de la série). Ces métadonnées peuvent être différents selon le producteur.
Le NGL fait exactement pareil, il n'y a pas de magie, ils ne peuvent pas ajouter des changements qui ne sont pas indiqués quelque part.
Pour l'analyse des séries, l'utilisateur est libre de choisir les métadonnées ou la méthode de détection bien sûr.

**Comment by EmilieKlein** [comment]
Ah mais je n'ai jamais parlé de saut !! Je ne parle absolument pas de matérialiser des sauts dont l'origine n'est pas recensées !! Je parle uniquement d'afficher tous les changements d'équipements recensés et renseignés dans les station.info et equivalent.. (qu'ils soient "pris en compte" ou non dans le traitement, ils sont renseignés) comme NGL donc.

**Comment by epointal** [comment]
Je note la demande, les infos sont dans le sitelog quand j'en trouve un
