### ISSUE TITLE
Maintien de la même emprise de la carte après une recherche

### ISSUE THREAD

**Issue by goe38** [terresolide/gnss-components-vjs#3]
Actuellement, si je modifie mes critères de recherche, et clique "Search", la carte revient sur une vue mondiale.
Je pense que pour l'utilisateur ça serait mieux de rester sur la même emprise de carte.

**Comment by epointal** [comment]
ok version 1.2.5. + ajouter bouton "vue d'ensemble" pour visualiser aussi l'ensemble des résultats
