### ISSUE TITLE
Suggestions: affichage de la provenance des données

### ISSUE THREAD

**Issue by EmilieKlein** [terresolide/gnss-components-vjs#32]
Il me semble important d'afficher l'origine des données et pas seulement l'origine de la solution (le traitement GAMIT/GLOBK - SPOTGINS) pour reconnaître le travail des gens/agences qui installent et maintiennent les stations qui produisent ces données. C'est aussi important pour pouvoir enquêter auprès des bonnes personnes lorsque les stations montrent des signaux bizarres (potentiellement liés a l'état de la station). C'est surtout une obligation imposée par un certain nombre de réseaux nationaux. 

- soit les stations sont installées par des réseaux nationaux (par ex. l'IGN français), auquel cas un logo, un contact générique et, s'il existe, un DOI, devraient apparaître  - j'imagine que les stations des Observatoires français tombent dans ce cas. 
Les sitelog sont normalement très bien remplis : 
--> site log au format IGS: section 12 et 13 du fichier log en pj pour la station BRFT. 
--> site log au format m3g : section 'siteOwner'. 

- soit les stations sont installées dans le cadre de projets de recherche, dans ce cas, le nom du PI du projet et, s'il existe, le DOI du jeu de données devrait être affichés

Finalement, dans les métadonnées, il faudrait qu'il y ait une section pour la provenance des données (logo, contact, DOI) et une section pour la provenance de la solution (solution, operators, DOI)

Ca implique probablement de réfléchir aux métadonnées et leur formats que les fournisseurs doivent soumettre pour valider l'intégration de la solution à l'interface de visualisation.

[BRFT00BRA_20230206.log](https://github.com/terresolide/gnss-components-vjs/files/11685768/BRFT00BRA_20230206.log)

**Comment by alvarosantamariagomez** [comment]
On peut ajouter l'agence responsable dans l'entête de la série si cette info est renseignée dans un sitelog.
Par contre, pas tous les sitelogs sont bien remplis et environ 16 % des stations du réseau SPOTGINS d'aujourd'hui n'ont pas de sitelog.
Dans ces cas on doit laisser le champ vide.

**Comment by EmilieKlein** [comment]
oui, plutôt un champ vide quand l'info est manquante que pas de champ du tout sur aucune station...! ;)

**Comment by alvarosantamariagomez** [comment]
ok pour moi
à discuter avec les autres producteurs SPOTGINS et UGA

**Comment by epointal** [comment]
Je peux afficher les informations du M3G quand elles existent:
siteOwner, onSiteContact, siteMetadataCustodian, moreInformation/primaryDataCenter, moreInformation/secondaryDataCenter

**Comment by EmilieKlein** [comment]
> ok pour moi
> à discuter avec les autres producteurs SPOTGINS et UGA

Si le but ultime c'est de proposer la diffusion de tous les produits proposés par la communauté française (sur la base du volontariat et sous reserve de validation de la qualité des produits en question), comme ca a l'air d'être le cas d'après ce que me disait Marianne, je pense qu'il faudrait en parler/y réfléchir a plus grande échelle que juste l'UGA et SPOTGINS. Si les critères que vous choisissez ne conviennent pas, ne sont pas suffisamment inclusifs pour les autres producteurs potentiels, ca pourrait poser problème..

**Comment by RaphaelGrandin** [comment]
D'accord avec toi @EmilieKlein, mais on doit commencer avec quelque chose. La plateforme évoluera au fur et à mesure, elle n'est pas figée. Donc je suggère que les discussions se poursuivent au sein du SNO RENAG (ou autre instance représentative de la communauté), et en attendant on va essayer de piocher dans M3G. @epointal va exposer quelques champs (ceux qui nous sembleront les plus pertinents par rapport à votre demande), et ensuite pourra itérer si il faut en rajouter ou en supprimer.

Question à vous deux (et aux autres): un site UNAVCO a été évoqué comme une source alternative pour trouver les infos sur les stations. Est-ce que quelqu'un pourrait nous pointer vers ce site? (ou mieux, s'il existe un webservice, nous l'indiquer?).

**Comment by EmilieKlein** [comment]
oui bien sur, tu as raison @RaphaelGrandin, il faut bien commencer.

Rapport a l'UNAVCO, la page pour la distribution de données est la: https://www.unavco.org/data/gps-gnss/data-access-methods/gnss-data-access-notebook/gnss-data-access-notebook.html mais du coup, c'est aussi pour la distribution de rinex. Ca a pas mal changé dans les dernières années, je ne maitrise plus trop, normalement, ils doivent avoir -entre autre- une page par projets scientifiques qui a produit des données avec le DOI associé, mais en fait ca ressemble beaucoup a ce qui a été par le GPSmob pour les DOI des campagnes sGPS, par ex: https://data.oreme.org/doi/view/745533fb-61d1-4fff-83ee-edc9586fc7ce

**Comment by epointal** [comment]
Premier affichage des "contacts" à valider, je viens de mettre à jour

**Comment by EmilieKlein** [comment]
Je trouve ca très bien -> pas affiché d'office sur la page (donc pas de surcharge) mais si on cherche l'info elle est la avec un menu déroulant, top. Je me demandais si certaines categories n'étaient pas redondantes mais en fait, en regardant différentes stations, je réalise que non, 2 categories peuvent être identiques mais pas tout le temps les memes 2. La difference entre On Site Contact et Site Metadata Custodian n'est cependant pas tres claire pour moi: le contact qui s'occupe physiquement de la station VS le contact qui gère les metadata ? 
Je trouve tres bien aussi d'avoir rajouté le MOID.

**Comment by mmetois** [comment]
Salut, j'ai vu que vous aviez avancé sur la question, super. 
En l'état, les informations du M3G qui sont indiquées dans "More Information" ne reprennent pas le DOI des réseaux par exemple. Celui de RENAG est là doi:10.15778/resif.rg il faudrait qu'on puisse le mettre quelque part.

**Comment by epointal** [comment]
J'ai créé une nouvelle issue pour les réseaux #43
