### ISSUE TITLE
Infos produit

### ISSUE THREAD

**Issue by goe38** [terresolide/gnss-components-vjs#4]
Pour ce qui est des métadonnées associées à une série temporelle de position, 3 retours:
- Le ProductType est défini comme "POSITTON" au lieu de "POSITION"
- Je renommerais "Phenomenon Time" en "Product date range"
- Je ne comprends pas le champ Products (G20/GRG), est-ce qu'il y a une explication quelque part? D'où vient cette info?

![Selection_234](https://github.com/terresolide/gnss-components-vjs/assets/60661334/d3bd03ba-d2ae-45c9-a0f6-a1b2e5cd4320)

**Comment by goe38** [comment]
Je ne fais que des retours négatifs, pour les choses qui me semblent améliorables, mais globalement c'est très bien, c'est déjà un super outil.

**Comment by epointal** [comment]
Fait version 1.2.5. Sauf products voir issue #5
