### ISSUE TITLE
champ Products (G20/GRG)

### ISSUE THREAD

**Issue by epointal** [terresolide/gnss-components-vjs#5]
Quelle est cette propriété? Faut-il la garder pour les produits UGA?

**Comment by alvarosantamariagomez** [comment]
G20/GRG est le label des produits précis d'orbite et horloge satellite utilisés pour le calcul SPOTGINS actuellement.  
Ces sont ces produits qui définissent le repère de référence des solutions PPP dans SPOTGINS.

Par ailleurs le terme "IGb20" est erroné.  
Ça doit venir des séries prè-SPOTGINS et donc pas officielles.

**Comment by epointal** [comment]
Ok, je supprime cette information des produits GAMIT-GLOBK
