### ISSUE TITLE
Outils interactifs: recherche, menu, nearest

### ISSUE THREAD

**Issue by lrolland06** [terresolide/gnss-components-vjs#50]
![image](https://github.com/terresolide/gnss-components-vjs/assets/88324524/f2e8694b-d4c5-4ad2-8e75-1594ce0a2753)
Suggestion: ajouter la possibilité de chercher un site à partir des 4 caractères.

**Comment by lrolland06** [comment]
![image](https://github.com/terresolide/gnss-components-vjs/assets/88324524/0f7157ca-68f6-48cd-a7cc-25f49ab4bffb)
Solutions, Product types et About sont inaccessibles.

**Comment by lrolland06** [comment]
![image](https://github.com/terresolide/gnss-components-vjs/assets/88324524/f8eda645-065d-4c84-83af-ee7faf137af1)
Très pratique pour avoir une vue globale des séries mises en ligne. Peut-on envisager de pouvoir télécharger un fichier csv et/ou json ?

**Comment by lrolland06** [comment]
Le nombre d'années/Years et le taux de remplissage/Fillrate mériteraient d'être indiqués dans le cartouche de visualisation de solution ici: 
![image](https://github.com/terresolide/gnss-components-vjs/assets/88324524/2e2ff411-1ff2-400e-acd9-30d09309a7f2)

**Comment by lrolland06** [comment]
Un bug sur l'outil "Nearest stations" ?
Pour 1000km de rayon, seule quelques stations s'affichent.
![image](https://github.com/terresolide/gnss-components-vjs/assets/88324524/5c4d9a1a-78f5-4125-b356-be2ff252acf5)

**Comment by epointal** [comment]
Oups, Ah j'ai un maxRecords=10 par défaut côté api (ce qui est peu) et je ne vais pas chercher la suite....

**Comment by epointal** [comment]
- [x] bug nearest station résolu
 - [x] taux de remplissage et nombre d'années affichés
 - [x] recherche textuelle ajoutée
 - [ ]  export csv de la liste de fichiers
 - [ ] page des solutions et pas des types de produit

**Comment by epointal** [comment]
- [x] export CSV

**Comment by epointal** [comment]
- [x] pages supprimées car vides pour le moment
