### ISSUE TITLE
visualisation carte générale

### ISSUE THREAD

**Issue by mmetois** [terresolide/gnss-components-vjs#6]
A mon avis, il faudrait qu'à l'échelle de la France metropolitaine on voit toutes les stations et pas des groupements comme dans la version actuelle. Il faut zoomer très fort sur une zone pour voir la position exacte des stations.

**Comment by epointal** [comment]
Je vais réduire le rayon pour voir si ça améliore quelque chose

**Comment by mmetois** [comment]
ça me va comme ça, merci.
