### ISSUE TITLE
Problèmes dans l'outil de requête

### ISSUE THREAD

**Issue by mmetois** [terresolide/gnss-components-vjs#7]
Si on rentre une date de début et de fin de la série temporelle, l'outil de requête sur une durée de la série ne peut il pas s'adapter tout seul à la durée maximale possible ? Sinon, quel est le critère de recherche qui a priorité ? La durée de la série ou la date de fin par exemple ? 

L'opérateur ALL n'a pas l'air de fonctionner. Il donne quelques stations lorsqu'on sélectionne la solution SPOTGINS mais ne correspond pas à ce à quoi on peut s'attendre, c'est à dire "tous les fournisseurs". Par exemple, si je sélectionne ALL avec la solution "GAMIT-GLOBK", rien n'apparait. 

Je n'arrive pas à chercher uniquement les stations qui ont des produits issus des deux solutions...

**Comment by epointal** [comment]
Oui, c'est normal, il faudrait supprimer le ALL. Je ne sais pas à quels producteurs il correspond, cette information provient des métadonnées.

**Comment by epointal** [comment]
Pour les dates, il recherche si il y a des données après la date de début et s'il y a des données avant la date de fin. Sans tenir compte de l'étendue. Il n'y a pas de priorité.
Je recrée de issues distinctes pour tous ces points.

**Comment by epointal** [comment]
Ne reste que le point ALL voir issue #9
