### ISSUE TITLE
Infos erronées ou manquantes

### ISSUE THREAD

**Issue by mmetois** [terresolide/gnss-components-vjs#8]
Le nom de la solution "GAMIT-GLOBK" pose problème car c'est le nom d'un logiciel. On peut imaginer que d'autres solutions calculées GAMIT-GLOBK mais différente de la solution EPOS-UGA viennent se greffer à terme à l'outil. Il faudrait changer pour EPOS-UGA ou un autre nom parlant. 

Il faudrait indiquer l'ellipsoide des coordonnées géographiques fournies sur les pages stations. A voir d'ailleurs si on est d'accord entre SPOTGINS et EPOS-UGA

Sur les pages stations, mettre le référentiel en plus gros, j'ai du chercher longtemps avant de voir que l'info était là 'Ref frame' juste au dessus des séries temporelles

Il manque une légende pour expliquer ce que sont les traits verticaux.

**Comment by epointal** [comment]
A discuter.
Je crée une nouvelle issue pour les traits verticaux

**Comment by epointal** [comment]
Une solution provisoire pour la légende des graphiques. #12
Reste le nom GAMIT-GLOBK #13
