### ISSUE TITLE
Opérateur ALL

### ISSUE THREAD

**Issue by epointal** [terresolide/gnss-components-vjs#9]
A quels producteurs correspond le ALL?
Partie de l'issue #7

**Comment by alvarosantamariagomez** [comment]
ALL ça veut dire que tous les producteurs SPOTGINS sont censés d'avoir calculé cette série au moins une fois entre 2005 et 2015. En tout, il y en a 5 séries comme ça.
Ces sont les séries que l'on utilise pour valider le calcul fait par les différents groups SPOTGINS.
Si le nom "ALL" pose problème, tu peux le remplacer par un des producteurs SPOTGINS, OMP par exemple.

**Comment by epointal** [comment]
Je pense que je peux remplacer par une liste mais je ne la connais pas pour le moment, les producteurs qui sont remontés sont EOST, GRGS, OMP, URL et UGA-CNRS

**Comment by epointal** [comment]
J'ai mis les ALL, à OMP
